# Generated by Django 5.1.4 on 2025-01-25 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daraz', '0002_product_customer_orderplaced_cart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_image',
            field=models.ImageField(max_length=255, upload_to='productimg'),
        ),
    ]
