# Generated by Django 5.1.4 on 2025-01-25 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daraz', '0003_alter_product_product_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='city',
        ),
        migrations.AlterField(
            model_name='product',
            name='product_image',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to='productimg'),
        ),
    ]
