# Generated by Django 5.1.4 on 2025-01-29 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daraz', '0004_remove_user_city_alter_product_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='gender',
            field=models.CharField(blank=True, choices=[('female', 'female'), ('male', 'male'), ('other', 'other')], max_length=50, null=True),
        ),
    ]
