# Generated by Django 5.1.4 on 2025-01-30 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daraz', '0005_customer_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='color',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
